// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqywhjgjkuyzkwyjiczu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxeXdoamdqa3V5emt3eWppY3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA0NjAsImV4cCI6MjA2NTQ5NjQ2MH0.5QpS_Ve3QEjyw8ViTOk1eHyWkkeBfGrb_zCQTHvL1Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);